import 'dart:html' as html;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:promise_guard/features/agreement_record/model/agreement_item_model.dart';

class PdfExportService {
  Future<void> exportAgreementRecord({
    required String callName,
    required String commercialTerm,
    required String resolution,
    required String stateChange,
    required String earlierEvidence,
    required String laterEvidence,
    required String missingEvidence,
    required String clarifyingQuestion,
    required List<AgreementItem> agreementItems,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          // Title
          pw.Text(
            'PromiseGuard — Agreement Record',
            style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            callName,
            style: const pw.TextStyle(fontSize: 13, color: PdfColors.grey600),
          ),
          pw.Divider(height: 24),

          // Details
          _section('Commercial Term', commercialTerm),
          _section('Status', resolution == 'confirmed' ? 'CONFIRMED' : 'NEEDS CONFIRMATION'),
          if (stateChange.isNotEmpty) _section('Commitment Path', stateChange),
          if (earlierEvidence.isNotEmpty)
            _section('Evidence', '$earlierEvidence → $laterEvidence'),
          if (missingEvidence.isNotEmpty) _section('Missing Evidence', missingEvidence),
          if (clarifyingQuestion.isNotEmpty)
            _section('Suggested Question', '"$clarifyingQuestion"'),

          // Agreement items table
          if (agreementItems.isNotEmpty) ...[
            pw.SizedBox(height: 16),
            pw.Text(
              'Agreement Items',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 8),
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              columnWidths: {
                0: const pw.FlexColumnWidth(2),
                1: const pw.FlexColumnWidth(2),
                2: const pw.FlexColumnWidth(2),
                3: const pw.FlexColumnWidth(3),
              },
              children: [
                // Header row
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: ['ITEM', 'VALUE', 'EVIDENCE', 'PARTICIPANTS']
                      .map((h) => pw.Padding(
                            padding: const pw.EdgeInsets.all(8),
                            child: pw.Text(h,
                                style: pw.TextStyle(
                                    fontSize: 9,
                                    fontWeight: pw.FontWeight.bold,
                                    color: PdfColors.grey700)),
                          ))
                      .toList(),
                ),
                // Data rows
                ...agreementItems.map(
                  (item) => pw.TableRow(
                    children: [item.item, item.value, item.evidence, item.participants]
                        .map((v) => pw.Padding(
                              padding: const pw.EdgeInsets.all(8),
                              child: pw.Text(v, style: const pw.TextStyle(fontSize: 10)),
                            ))
                        .toList(),
                  ),
                ),
              ],
            ),
          ],

          pw.SizedBox(height: 24),
          pw.Text(
            'Generated by PromiseGuard · promiseguard.web.app',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
          ),
        ],
      ),
    );

    final bytes = await pdf.save();
    final blob = html.Blob([bytes], 'application/pdf');
    final url = html.Url.createObjectUrlFromBlob(blob);
    html.AnchorElement(href: url)
      ..setAttribute('download', '${callName.replaceAll(' ', '_')}_agreement.pdf')
      ..click();
    html.Url.revokeObjectUrl(url);
  }

  pw.Widget _section(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 10),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 130,
            child: pw.Text(
              label.toUpperCase(),
              style: pw.TextStyle(
                  fontSize: 8,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.grey600,
                  letterSpacing: 0.5),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value, style: const pw.TextStyle(fontSize: 11)),
          ),
        ],
      ),
    );
  }
}