// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXIm9BRpp4gtIwCSNQZZRwpSPeVI6rH_I',
    appId: '1:364103523068:web:3e57c6a2a8b90c6c1ad579',
    messagingSenderId: '364103523068',
    projectId: 'promise-guard',
    authDomain: 'promise-guard.firebaseapp.com',
    storageBucket: 'promise-guard.firebasestorage.app',
    measurementId: 'G-82209074B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiqvB0ipaV0oh_y_uCF39tvl_O4WhXuI0',
    appId: '1:364103523068:android:656ef909990460f61ad579',
    messagingSenderId: '364103523068',
    projectId: 'promise-guard',
    storageBucket: 'promise-guard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRwUdulXSStaOh-2Az6dYMiCrUZEBSUwU',
    appId: '1:364103523068:ios:7ad9be988a6fe7f61ad579',
    messagingSenderId: '364103523068',
    projectId: 'promise-guard',
    storageBucket: 'promise-guard.firebasestorage.app',
    iosBundleId: 'com.example.promiseGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRwUdulXSStaOh-2Az6dYMiCrUZEBSUwU',
    appId: '1:364103523068:ios:7ad9be988a6fe7f61ad579',
    messagingSenderId: '364103523068',
    projectId: 'promise-guard',
    storageBucket: 'promise-guard.firebasestorage.app',
    iosBundleId: 'com.example.promiseGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXIm9BRpp4gtIwCSNQZZRwpSPeVI6rH_I',
    appId: '1:364103523068:web:b25cca2174c01de81ad579',
    messagingSenderId: '364103523068',
    projectId: 'promise-guard',
    authDomain: 'promise-guard.firebaseapp.com',
    storageBucket: 'promise-guard.firebasestorage.app',
    measurementId: 'G-YG3YF48L28',
  );
}
